language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
env:
  global:
    secure: djEYH2/kMnxHnDxqdVqLe0JCwmWd9mHNe+i73JQZmw/0p2OId3YUdX/wu24NoVxMRlJ6SM1Dx/moqpaxFcZHX7rHoJ7flbbPIeQaDy3kXigF1+jR/2c5qIoRF0Xq41t6FLBJrhX9wlOj4rkJSGqt7xpBtMdSjunqwVLfcvIUGtQ=
after_success:
- bash .travis/after_success
